CREATE TABLE `Mst_MedicalRecord_Medication` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`PetID` INT NULL DEFAULT NULL,
	`CategoryID` INT NULL DEFAULT NULL,
	`ProductID` INT NULL DEFAULT NULL,
	`ExpiryDate` DATETIME NULL DEFAULT NULL,
	`Status` INT NULL DEFAULT NULL,
	`Description` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`UpdatedDate` DATETIME NULL DEFAULT NULL,
	`UpdatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;