CREATE TABLE `mst_doctor_services` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`DoctorID` INT NULL DEFAULT NULL,
	`ServicesID` INT NULL DEFAULT NULL,
	`Status` INT NULL DEFAULT NULL,
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
