CREATE TABLE `mst_profile_avatar` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`EntityGroup` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`EntitySubGroup` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`AvatarFileName` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`AvatarFilePath` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Status` INT NULL DEFAULT NULL,
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`UpdatedDate` DATETIME NULL DEFAULT NULL,
	`UpdatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=10
;
