CREATE TABLE `mst_pets_ranges` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Species` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`RangeType` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`RangeStart` DECIMAL(20,4) NULL DEFAULT NULL,
	`RangeEnd` DECIMAL(20,4) NULL DEFAULT NULL,
	`Status` INT NULL DEFAULT NULL,
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`UpdatedDate` DATETIME NULL DEFAULT NULL,
	`UpdatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	INDEX `ID` (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
