CREATE TABLE `Txn_TreatmentPlan` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `PetID` INT NULL DEFAULT NULL,
    `TreatmentPlanID` INT NULL DEFAULT NULL,
    `PlanName` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    `TreatmentStart` DATETIME NULL DEFAULT NULL,
    `TreatmentEnd` DATETIME NULL DEFAULT NULL,
	`TotalCost` DECIMAL(10,2) NULL DEFAULT NULL, 
    `Status` INT NULL DEFAULT NULL,
    `CreatedDate` DATETIME NULL DEFAULT NULL,
    `CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    `UpdatedDate` DATETIME NULL DEFAULT NULL,
    `UpdatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;