CREATE TABLE `mst_treatmentplan` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',    
	`BranchID` INT NULL DEFAULT NULL,
	`Remarks` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',    
	`TotalPrice` DECIMAL(18,2) NULL DEFAULT NULL,
	`Status` INT NULL DEFAULT NULL,
	`IsDeleted` INT NULL DEFAULT NULL,
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`UpdatedDate` DATETIME NULL DEFAULT NULL,
	`UpdatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;