CREATE TABLE `Mst_MedicalRecord_VaccinationSurgery` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`PetID` INT NULL DEFAULT NULL,
	`CategoryID` INT NULL DEFAULT NULL,
	`ServiceID` INT NULL DEFAULT NULL,
	`Type` INT NULL DEFAULT NULL,
	`DueDate` DATETIME NULL DEFAULT NULL,
	`Description` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Remarks` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`IsDeleted` INT NULL DEFAULT NULL,
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`UpdatedDate` DATETIME NULL DEFAULT NULL,
	`UpdatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;