CREATE TABLE `Txn_Stock_UploadLog` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ActionType` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Filename` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Status` INT NULL DEFAULT NULL,
	`BranchID` INT NULL DEFAULT NULL,
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `Txn_Stock_Upload` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`UploadLogID` INT NULL DEFAULT NULL,
	`SKU` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    `PricePerQty` DECIMAL(10,2) NULL DEFAULT NULL, 
	`SerialNo` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;