ALTER TABLE mst_branch
ADD COLUMN Postcode VARCHAR(20) NULL DEFAULT NULL AFTER `UpdatedBy`,
ADD COLUMN City VARCHAR(100) NULL DEFAULT NULL AFTER `Postcode`,
ADD COLUMN State VARCHAR(100) NULL DEFAULT NULL AFTER `City`;